config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#welcome'
  resources :users, :only => [:new, :create, :index]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :places
  resources :packages
  resources :itineraries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  has_and_belongs_to_many :user
  has_and_belongs_to_many :packages
end

app/models/package.rb
class Package < ApplicationRecord
  has_many :places, dependent: :nullify
  has_and_belongs_to_many :itineraries
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :package, :optional => true

  geocoded_by :location
  after_validation :geocode, :if => :location_changed?
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_and_belongs_to_many :itineraries
  has_many :packages, :through => :itineraries

  validates :email, :presence => true, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

  def check_for_admin
    redirect_to root_path unless @current_user.present? && @current_user.admin?
  end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
before_action :check_for_login, :only => [:index]
before_action :check_for_admin, :only => [:edit, :destroy]

  def index
    if @current_user.present? && @current_user.admin?
      @itineraries = Itinerary.all.order(:date)
    else
      @user = User.where("email = ?", @current_user.email)
    end
  end

  def new
    @itinerary = Itinerary.new
  end

  def create
    itinerary = Itinerary.create itinerary_params
    redirect_to itineraries_path
  end

  def edit
    @itinerary = Itinerary.find params[:id]
    @user = params[:user_id]
  end

  def update
    itinerary = Itinerary.find params[:id]
    itinerary.update itinerary_params
    redirect_to itineraries_path
  end

  def destroy
    itinerary = Itinerary.find params[:id]
    itinerary.destroy
    redirect_to itineraries_path
  end

  private
  def itinerary_params
    params.require(:itinerary).permit(:date, :user_ids, package_ids:[])
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
before_action :check_for_admin, :only => [:new, :edit, :destroy]

  def index
    # sort by created at
    @packages = Package.all.order('created_at')
  end

  def new
    @package = Package.new
  end

  def create
    package = Package.create package_params
    redirect_to package
  end

  def edit
    @package = Package.find params[:id]
  end

  def update
    package = Package.find params[:id]
    package.update package_params
    redirect_to package
  end

  def show
    @package = Package.find params[:id]
  end

  def destroy
    package = Package.find params[:id]
    package.destroy
    redirect_to packages_path
  end

  private
  def package_params
    params.require(:package).permit(:name, :time, :price, place_ids:[])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
before_action :check_for_admin, :only => [:new, :edit, :destroy]

  def index
    @places = Place.all.order('created_at')
  end

  def new
    @place = Place.new
  end

  def create
    place = Place.new place_params
    #to upload cloudinary link in database
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      place.image = req["public_id"]
      place.save
    end
    #checks if there was a package selected
    if params[:place][:package_id] != ''
      package = Package.find params[:place][:package_id]
      package.places << place
    end
    redirect_to place
  end

  def edit
    @place = Place.find params[:id]
  end

  def update
    place = Place.find params[:id]
    #to upload cloudinary link in database
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      place.image = req["public_id"]
    end
    place.update_attributes place_params
    place.save
    redirect_to place
  end

  def show
    @place = Place.find params[:id]
  end

  def destroy
    place = Place.find params[:id]
    place.destroy
    redirect_to places_path
  end

  private
  def place_params
    params.require(:place).permit(:name, :location, :image, :package_id)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid email address or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id #Log the user in
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/itineraries/_form.html.erb
<%= form_for @itinerary do |f| %>
  <fieldset class="form-group">
    <%= f.label :date %>
    <%= f.date_field :date, :required => true, :autofocus => true %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.collection_check_boxes :package_ids, Package.all, :id, :name do |b|%>
    <div class="custom-control custom-checkbox">
      <%= b.check_box %>
      <%= b.label %>
    </div>
    <% end %>
  </fieldset>

  <% if @current_user.admin? %>
    <%= f.hidden_field :user_ids, :value => @user %>
  <% else %>
    <%= f.hidden_field :user_ids, :value => @current_user.id %>
  <% end %>
  <%= f.submit nil, :class =>'btn btn-primary'%>
<% end %>

app/views/itineraries/edit.html.erb
<h2>Edit Itinerary</h2>

<%= render :partial => 'form'  %>

app/views/itineraries/index.html.erb
<%# checks if user logged in is an admin or not. admin can view all itineraries. other users can only see their own itinerary %>
<% if @current_user.admin? %>

  <h2 class="text-center">All Itineraries</h2>

  <%# To display 3 columns per row %>
  <% @itineraries.each_slice(3) do |itineraries| %>
    <div class="row">
      <%# To put itinerary on one column %>
      <% itineraries.each do |itinerary| %>
        <div class="col-md-4">
          <p class="text-center"><%= itinerary.date.strftime '%A, %B %e, %Y' %></p>
          <ul class="list-unstyled">
          <% itinerary.user.each do |user| %>
            <li><%= user.email %> <%= link_to "Edit", edit_itinerary_path(itinerary, :user_id => user.id), :class => "d-inline-block" %>
            <%= button_to "Delete", itinerary_path(itinerary, :user_id => user.id), :method => 'delete', :data => { :confirm => "Are you sure?" }, :class => "d-inline-block btn btn-danger btn-sm" %>
            </li>
            <ul>
              <% itinerary.packages.each do |package| %>
                <li><%= link_to package.name, package_path(package) %></li>
              <% end %>
            </ul>
          <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  <% end %>
  <%# end admin view %>

<% else %>

  <%# Non-admin view %>
  <h2 class="text-center">My Itineraries</h2>

  <%# Get user first and display 3 itineraries in columns per row %>
  <% @user.each do |user| %>
    <% user.itineraries.order('date').each_slice(3) do |itineraries| %>
      <div class="row">
        <% itineraries.each do |itinerary| %>
          <div class="col-md-4">
            <p><%= itinerary.date.strftime '%A, %B %e, %Y' %></p>
            <ul>
            <% itinerary.packages.each do |package| %>
              <li><%= link_to package.name, package_path(package) %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>

<% end %>

app/views/itineraries/new.html.erb
<h2>New Itinerary</h2>

<%= render :partial => 'form'  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ultimate Coron Experience</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= cloudinary_js_config %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# for google maps! %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+Rails.application.secrets.google_maps_api_key %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head_tags) %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <%= link_to image_tag("http://www.ultimatecoronexperience.com/wp-content/uploads/2013/12/LOGO.png"), root_path, class: "navbar-brand" %>
      <ul class="nav navbar-nav ml-auto">
          <% if @current_user.present? %>
          <li class="nav-item nav-link text-light" >Welcome <%= @current_user.email %>!</li>
          <% if @current_user.admin? %>
            <li class="nav-item nav-link" ><%= link_to "Tours", packages_path, :class => "text-light" %></li>
            <li class="nav-item nav-link" ><%= link_to "Add Tour", new_package_path, :class => "text-light" %></li>
            <li class="nav-item nav-link" ><%= link_to "Places", places_path, :class => "text-light" %></li>
            <li class="nav-item nav-link" ><%= link_to "Add Place", new_place_path, :class => "text-light" %></li>
            <li class="nav-item nav-link" ><%= link_to "All Itineraries", itineraries_path, :class => "text-light" %></li>
          <% else %>
            <li class="nav-item nav-link" ><%= link_to "Tours", packages_path, :class => "text-light" %></li>
            <li class="nav-item nav-link" ><%= link_to "Places", places_path, :class => "text-light" %></li>
            <li class="nav-item nav-link" ><%= link_to "My Itineraries", itineraries_path, :class => "text-light" %></li>
            <li class="nav-item nav-link" ><%= link_to "Add Itinerary", new_itinerary_path, :class => "text-light" %></li>
          <% end %>
            <li class="nav-item nav-link" ><%= link_to "Sign out", login_path, :method => 'delete', :class => "text-light" %></li>
        <% else %>
          <%= link_to "Tours", packages_path, class: "nav-item nav-link" %>
          <%= link_to "Places", places_path, class: "nav-item nav-link" %>
          <%= link_to "Sign up", new_user_path, class: "nav-item nav-link"  %>
          <%= link_to "Sign in", login_path, class: "nav-item nav-link" %>
        <% end %>
      </ul>
    </nav>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/welcome.html.erb
<h1>Ultimate Coron Experience</h1>


<%= image_tag "https://www.ultimatecoronexperience.com/wp-content/uploads/2013/12/ABOUT-US-PIC2.jpg", class: "img-fluid" %>

app/views/places/_form.html.erb
<%= form_for(@place, :html => {:multipart => true}) do |f| %>
<fieldset class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, :required => true, :autofocus => true, :class => 'form-control' %>
</fieldset>
<fieldset class="form-group">
  <%= f.label :location %>
  <%= f.text_field :location, :class => 'form-control' %>
</fieldset>
<fieldset class="form-group">
  <%= f.collection_radio_buttons :package_id, Package.all, :id, :name  do |b| %>
  <div class="form-check">
    <%= b.radio_button %>
    <%= b.label %>
  </div>
  <% end %>
</fieldset>
<fieldset class="form-group">
  <%= f.label :image %>
  <%= f.cl_image_upload :image, :class => 'form-control' %>
</fieldset>
<%= f.submit nil, :class => 'btn btn-primary' %>
<% end %>

app/views/places/edit.html.erb
<h2>Edit Place</h2>

<%= render :partial => 'form' %>

app/views/places/index.html.erb
<h2 class="text-center">Places to Explore in Coron</h2>

<%# To display 3 places in columns per row %>
<% @places.each_slice(3) do |places| %>
<div class="row">
  <%# To get a place in a column %>
  <% places.each do |place| %>
  <div class="col-md-4">
    <%= link_to place.name, place_path(place) %>
    <p>Included in our <%= link_to place.package.name, package_path(place.package) if place.package.present? %></p>
    <%= cl_image_tag(place.image, class: "img-thumbnail") if place.image.present? %>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non, magni, sit?</p>
  </div>
  <% end %>
</div>
<% end %>

app/views/places/new.html.erb
<h2>Add Place</h2>

<%= render :partial => 'form' %>

app/views/places/show.html.erb
<%# for google maps api! %>
<% if @place.longitude.present? %>
  <% provide :head_tags do %>
    <meta name='turbolinks-visit-control' content='reload'>
    <script>
    document.addEventListener("DOMContentLoaded", function(){
        initMap(<%=@place.latitude%>, <%=@place.longitude%>)
    });
    </script>
  <% end %>
<% end %>

<h2 class="text-center"><%= @place.name %></h2>

<!-- only display this for admin -->
<div class="text-center">
  <% if @current_user.present? %>
    <%= link_to "Edit Place", edit_place_path, :class => "d-inline-block" if @current_user.admin? %>
    <%= button_to "Delete Place", @place, :method => 'delete', :data => { :confirm => "Are you sure?"}, :class => "d-inline-block btn btn-danger btn-sm" if @current_user.admin? %>
  <% end %>
</div>

<ul class="list-inline text-center">
  <li class="list-inline-item">Included in <%= link_to @place.package.name, package_path(@place.package) if @place.package.present? %></li>
</ul>

<div class="row">
  <div class="col-md-6">
    <%= cl_image_tag(@place.image, class: "img-fluid mx-auto d-block") if @place.image.present?%>
  </div>
  <div class="col-md-6">
    <div id="map"></div>
  </div>
</div>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint, vitae, aliquid. Laborum perferendis modi quidem asperiores provident facere libero velit. Voluptatem impedit, aperiam voluptatum sequi facere culpa quisquam, vel suscipit!</p>

app/views/session/new.html.erb
<h1>Login</h1>
<% if flash[:error].present? %>
  <h2><%= flash[:error] %></h2>
<% end %>

<%= form_tag login_path do %>
<fieldset class="form-group">
  <%= label_tag :email %>
  <%= email_field_tag :email, nil, :class => 'form-control' %>
</fieldset>

<fieldset class="form-group">
  <%= label_tag :password %>
  <%= password_field_tag :password, nil, :class => 'form-control' %>
</fieldset>
  <%= submit_tag 'Sign in', :class =>'btn btn-primary'  %>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up!</h2>
<% if @user.errors.any? %>
  <ol>
    <%  @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for @user do |f| %>
<fieldset class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, :required => true, :autofocus => true, :class => 'form-control' %>
</fieldset>

<fieldset class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, :required => true, :class => 'form-control' %>
</fieldset>

<fieldset class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, :required => true, :class => 'form-control' %>
</fieldset>

  <%= f.submit "Sign up!", :class => 'btn btn-primary' %>
<% end %>